[package]
name = "multicell"
version = "0.1.0"
authors = ["alanhkarp <alanhkarp@gmail.com>"]

[dependencies]
crossbeam = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9.9"
rand = "*" # Or a specific version
error-chain = "*"
eval = "^0.4"