/* automatically generated by rust-bindgen */
/* edited */

#[allow(non_snake_case)]
#[allow(unused)]
pub mod port {

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct buf_desc_t {
    pub len: u32,
    pub frame: *mut u8,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecnl_port_t {
    pub port_module_id: u32,
    pub port_sock: *const ::std::os::raw::c_void,
    pub port_esock: *const ::std::os::raw::c_void,
    pub port_name: *const ::std::os::raw::c_char,
    pub port_id: u32,
    pub port_up_down: ::std::os::raw::c_int,
}

unsafe impl Send for ecnl_port_t {}
unsafe impl Sync for ecnl_port_t {}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecnl_event_t {
    pub event_module_id: u32,
    pub event_port_id: u32,
    pub event_cmd_id: ::std::os::raw::c_int,
    pub event_n_msgs: u32,
    pub event_up_down: ::std::os::raw::c_int,
}

#[link(name = ":port.o")]
#[link(name = ":ecnl_proto.o")]
#[link(name = ":libnl-3.so")]
#[link(name = ":libnl-genl-3.so")]

extern "C" {
    pub fn ecnl_init(debug: bool) -> ::std::os::raw::c_int;
    pub fn port_create(port_id: u32) -> *const ecnl_port_t;
    pub fn port_destroy(port: *const ecnl_port_t);

    pub fn port_do_read_async(port: *const ecnl_port_t, actual_buf: *mut buf_desc_t);
    pub fn port_do_read(port: *const ecnl_port_t, actual_buf: *mut buf_desc_t, nsecs: ::std::os::raw::c_int);
    pub fn port_do_xmit(port: *const ecnl_port_t, buf: *mut buf_desc_t);
    pub fn port_update(port: *const ecnl_port_t);

    pub fn port_get_event(port: *const ecnl_port_t, event: *mut ecnl_event_t);

    pub fn port_dumpbuf(port: *const ecnl_port_t, tag: *const ::std::os::raw::c_char, buf: *mut buf_desc_t);
}

}
