#---------------------------------------------------------------------------------------------
 #  Copyright © 2016-present Earth Computing Corporation. All rights reserved.
 #  Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#---------------------------------------------------------------------------------------------
FROM ec/baseline

COPY Cargo.toml Cargo.toml
COPY src src
RUN cargo build --release --bin cell --features="cell"
CMD ["target/release/cell"]
