#---------------------------------------------------------------------------------------------
 #  Copyright © 2016-present Earth Computing Corporation. All rights reserved.
 #  Licensed under the MIT License. See LICENSE.txt in the project root for license information.
#---------------------------------------------------------------------------------------------

CFLAGS += -g
CFLAGS += -fPIC
CFLAGS += -I/usr/include/libnl3
LDLIBS += -lnl-genl-3 -lnl-3

default: user

