user-build:
	@tput setaf 1
	@echo "    user-build"
	@tput sgr0
	gcc -c -fPIC -I../../NALDD/entl_drivers/ecnl_device ecnl.c -o ecnl.a

user-clean:
	@tput setaf 1
	@echo "    user-clean"
	@tput sgr0
	rm -rf *.out
